#!/usr/bin/env python3
"""使用 Playwright 浏览器会话下载 YouTube 音频"""

import subprocess
import json
import os
import sys
from pathlib import Path

# 添加 Playwright 的路径
sys.path.insert(0, r'D:\projects\colleague-skill\.claude\mcp')

def get_playwright_cookies():
    """从 Playwright 浏览器获取 cookies"""
    try:
        from playwright.sync_api import sync_playwright

        pw = sync_playwright().start()
        # 使用用户 Chrome 的 persistent context
        context = pw.chromium.launch_persistent_context(
            'C:/Users/gold3/AppData/Local/Google/Chrome/User Data/Default',
            headless=False,
            viewport={'width': 1280, 'height': 720},
        )

        # 访问 YouTube 获取 cookies
        page = context.new_page()
        page.goto("https://www.youtube.com", timeout=30000)
        page.wait_for_timeout(3000)

        # 获取所有 cookies
        cookies = context.cookies()

        # 写入 cookies 文件 (netscape 格式)
        cookie_file = "D:/projects/colleague-skill/zsxq_data/youtube_henren778/cookies.txt"
        with open(cookie_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by get_playwright_cookies.py\n\n")
            for c in cookies:
                domain = '.' + c['domain'] if not c['domain'].startswith('.') else c['domain']
                flag = 'TRUE' if c['hostOnly'] else 'FALSE'
                path = c['path'] or '/'
                secure = 'TRUE' if c['secure'] else 'FALSE'
                expiry = int(c['expires']) if c['expires'] else 0
                name = c['name']
                value = c['value']
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

        print(f"已导出 {len(cookies)} 个 cookies")

        pw.stop()
        return cookie_file

    except Exception as e:
        print(f"错误: {e}")
        return None

def download_video(video_url, output_dir, cookies_file):
    """使用 yt-dlp 和 cookies 下载音频"""
    output_template = f"{output_dir}/%(id)s.%(ext)s"
    cmd = [
        'yt-dlp',
        '--cookies', cookies_file,
        '-f', 'bestaudio/best',
        '--extract-audio',
        '--audio-format', 'mp3',
        '--audio-quality', '0',
        '--output', output_template,
        '--no-playlist',
        '--quiet',
        video_url
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            return True, "成功"
        else:
            return False, result.stderr[:200] if result.stderr else "未知错误"
    except Exception as e:
        return False, str(e)

def main():
    base_dir = "D:/projects/colleague-skill/zsxq_data/youtube_henren778"
    audio_dir = f"{base_dir}/audio"
    os.makedirs(audio_dir, exist_ok=True)

    # 1. 获取 cookies
    print("正在从 Playwright 浏览器获取 cookies...")
    cookies_file = get_playwright_cookies()

    if not cookies_file or not os.path.exists(cookies_file):
        print("获取 cookies 失败")
        return

    # 2. 读取视频列表
    with open(f"{base_dir}/videos.json", 'r', encoding='utf-8') as f:
        data = json.load(f)

    videos = data['videos']
    print(f"共 {len(videos)} 个视频，开始下载...")

    success = 0
    failed = 0

    for i, video in enumerate(videos):
        video_id = video.get('id')
        url = video.get('url')
        title = video.get('title', '')[:40]

        if not video_id or not url:
            print(f"[{i+1}/{len(videos)}] 跳过（无URL）: {title}...")
            continue

        # 检查是否已下载
        if os.path.exists(f"{audio_dir}/{video_id}.mp3"):
            print(f"[{i+1}/{len(videos)}] 已存在: {title}...")
            success += 1
            continue

        print(f"[{i+1}/{len(videos)}] 下载: {title}...")

        ok, msg = download_video(url, audio_dir, cookies_file)
        if ok:
            print(f"  ✓ 成功")
            success += 1
        else:
            print(f"  ✗ 失败: {msg}")
            failed += 1

    print(f"\n完成！成功: {success}, 失败: {failed}")
    print(f"音频目录: {audio_dir}")

if __name__ == '__main__':
    main()
